

Orientation is giving by brackets
Shapes of vectors are real numbers
Dimensions are always (rows, Columns)







In [2]:
import numpy as np

In [3]:
asArray = np.array([1,2,3,4], dtype=np.int32)
asArray


array([1, 2, 3, 4], dtype=int32)

In [4]:
rowVec = np.array([ [1,2,3] ]) # row
rowVec

array([[1, 2, 3]])

In [5]:
a  = np.array([4,5,6])
b = np.array([7,8,9])
c = np.array([10,11,12,16])
v = np.array([[4,5,6]])
w  = np.array([[10,20,30]]).T

w+m

NameError: name 'm' is not defined

In [ ]:
new = np.array([[1,2,3]])
new

In [ ]:
s = 2.0
a = [3,4,5]
b = np.array(a)

In [ ]:
# a is stored as regular array
# if we change the data type then we cant multiply 
a * s

In [ ]:
# here the data is stored as a vector
# here numpy assigns the data type to be float
s * b

In [ ]:
# Dimensions and Magnitude
v = np.array([1,2,3,4,5,6])
v_dim = len(v)
v_mag = np.linalg.norm(v)
print(v_mag, v_dim)


In [12]:
# dot product
s = 0
v = np.array([1,2,3,4,5,6])
w = np.array([3,4,65,7,4,5])
np.dot(v, w)



284

In [13]:
np.dot(s*v, w)

0

In [19]:
a = np.array([ 0,1,2 ])
b = np.array([ 3,5,8 ])
c = np.array([ 13,21,34 ])
res1 = np.dot(a, b+c)
res1
a

array([0, 1, 2])

In [ ]:
def get_data() -> int:
    return 10

if get_data() == 10:
    print(False)
else:
    print(True)

In [ ]:
# get the data from the user
def check_data():
    # we need to make sure that we can include
