In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
import typing


The flexible types of python comes with a cost. Since each item in the list must contained its own type

### Fixed Type Arrays
Numpy arrays contained only one type of data. Usually integers. 


In [8]:
np.zeros(10 , dtype=np.int32).reshape([5,2])

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [19]:
rgn = np.random.default_rng(seed=1701)
x1 = rgn.integers(10, size=6)
x2 = rgn.integers(10, size=(3, 4))

In [15]:
print(x1.ndim,
x1.shape, 
x1.size,
x1.dtype)

1 (6,) 6 int64


Array indexing

In [20]:
x2[2, 1]

0

In [22]:
x1[::2]

array([9, 0, 8])

Numpy arrays are returned as views not copies. We can use the copy function to make changes to only few parts but not changing the original array. 

* Resaphing an array
*   We can use the reshape function and specify how many rows and columns

In [24]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
# we can also specify where or what axis we want to concatenate our data. 
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [26]:
# its better to use vstack or hstack for arrays of different dimensions. 
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting Arrays
We can use the split, vsplit and hsplit functions to split array into subarrays

In [48]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [1, 6])
print(x1, x2, x3)

[1] [ 2  3 99 99  3] [2 1]


## Computational Power
Vectorize operations using Ufuncts. This is more efficient for processing 

The arithmetic operations in numpy are wrappers. Meaning that, each time we use +  - / we are using the wrapper for functions such as add, substract, divide. 

We can also use scipy.special. This module contains functions that are useful for mathematical operations. 



## Agregation

In [69]:
### Summing Array of data
rng = np.random.default_rng(125)
L = rng.random(100)
np.sum(L)


49.12521715012502