In [13]:
import numpy as np
import matplotlib.pyplot as plt


In [14]:
i_hat = np.array([[0,1],[1,3]])
j_hat = np.array([[-1,0],[4,5]])
i_hat.dot(j_hat)

array([[ 4,  5],
       [11, 15]])

### Determinants
How does a vector space changes based on a linear transformation
Determinants can tell you if you have a linear dependent matrix
If we get a 0 determinant then it means that the matrix has been reduce

In [15]:
from numpy.linalg import det
i_j_multiplied = np.dot(i_hat,j_hat)
determinants =  det(i_j_multiplied)
determinants

5.000000000000003

In [16]:
# determinants can also be negative
i = np.array([[-12,34], [32, 23]])
j = np.array([[134,34], [43, 3]])
dot_multiplied = np.dot(i,j)
determinants = det(dot_multiplied)
determinants

1445839.999999999

### Inverse Matrix 
Undoes the transformation of another matrix

### Diagonal Matrix
### Triangular Matrix


In [25]:
# Ax = B
from numpy.linalg import inv
A = np.array([[4,2,4],[5,3,7],[9,3,6]])
A_inv = inv(A)
B = np.array([44,56,72])
print(A_inv.dot(B   ))

[ 2. 34. -8.]


### Matrix Decomposition
Is breaking up a matrix into its basic. Like 10 is 5x2
Is like factoring. Only works in square matrixes
$$ Av = \lambda{v} v $$


In [30]:
from numpy import array, diag
from numpy.linalg import eig
A = array([[1,2],[4,5]])
eigenvals , eigenvect = eig(A)
eigenvals
eigenvect

array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]])