In [12]:
import random

import pandas as pd
import numpy as np
from numpy.linalg import inv, qr
import matplotlib.pyplot as plt
import random
from sklearn.linear_model import LinearRegression
from pydantic import BaseModel


### Machine Learning Questions


What is the best fit of the data
How do we know that we get the best fit

In [13]:
df = pd.read_csv('https://bit.ly/3goOAnt', delimiter=',')
df

x   y
0   1   5
1   2  10
2   3  10
3   4  15
4   5  14
5   6  15
6   7  19
7   8  18
8   9  25
9  10  23

In [14]:
X =  df.values[:,:-1].flatten()
x_1 = np.vstack((X, np.ones(len(X)))).T
x_1

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.]])

In [15]:
Y = df.values[:, -1].flatten()
Y

array([ 5, 10, 10, 15, 14, 15, 19, 18, 25, 23])

In [16]:
b = inv(x_1.transpose() @ x_1) @ (x_1.transpose() @ Y)
b

array([1.93939394, 4.73333333])

In [17]:
y_predict = x_1.dot(b)
y_predict

array([ 6.67272727,  8.61212121, 10.55151515, 12.49090909, 14.43030303,
       16.36969697, 18.30909091, 20.24848485, 22.18787879, 24.12727273])

In [18]:
Q, R = qr(x_1)
R

array([[-19.62141687,  -2.80305955],
       [  0.        ,  -1.46385011]])

In [19]:
Q @  R

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.]])

In [37]:
# gradiant Descent
def f(x):
    return (x-3) ** 2 + 4

def dx_f(x):
    return 2*(x-3)

L = 0.001
iterations = 100_000
x = random.randint(-15, 15)


13

In [50]:
for i in range(iterations):
    d_x = dx_f(x)
    x -= L * d_x
print(x, f(x))

3.000000000000111 4.0
